# Basic
site_name: Open Geodata
site_author: Michel Metran
site_description: O e-SAJ (Sistema de Automação da Justiça) é um portal do TJSP, desenvolvido pela Softplan, que facilita a troca de informações e agiliza o trâmite processual. O pacote pyESAJ foi desenvolvido para permitir a interação com o e-SAJ por meio do python.
site_url: https://opengeodata.readthedocs.io/pt/latest/
copyright: |
  &copy; 2025 <a href="https://github.com/michelmetran/"  target="_blank" rel="noopener">Michel Metran</a>

# GitHub Repo Link
repo_url: https://github.com/michelmetran/open-geodata

docs_dir: "docs" # Default docs
site_dir: "site" # Default site

# NavBar
# Opcional
nav:
  - Home: index.md
  - GeoServer: pages/geoserver.md
  - GeoServer: pages/arcgis.md
  - Outros: pages/outros.md
  - Ambiente de Desenvolvimento: pages/ambiente_desenvolvimento.md

  - Dados (Brasil):
      - BR.ANM: pages/dados/br/amn.md
      - BR.ANM (Class): pages/dados/br/amn_class.ipynb
      - BR.ANM (Pooch): pages/dados/br/amn_pooch.ipynb
      - BR.ANEEL (ArcGIS): pages/dados/br/aneel_arcgis.ipynb
      - BR.ANP (GeoServer): pages/dados/br/anp_geoserver.ipynb
      - BR.BDGEx: pages/dados/br/bdgex.md
      - BR.CNUC (Pooch): pages/dados/br/cnuc_pooch.ipynb
      - BR.DNIT (GeoServer): pages/dados/br/dnit_geoserver.ipynb
      - BR.FUNAI (GeoServer): pages/dados/br/funai_geoserver.ipynb
      - BR.IBAMA (GeoServer): pages/dados/br/ibama_geoserver.ipynb
      - BR.ICMBio (Pooch): pages/dados/br/icmbio_pooch.ipynb
      - BR.IBGE (Class): pages/dados/br/ibge_class.ipynb
      - BR.IBGE (GeoServer): pages/dados/br/ibge_geoserver.ipynb
      - BR.IBGE (Pooch): pages/dados/br/ibge_pooch.ipynb
      - BR.INPE (GeoServer): pages/dados/br/inpe_geoserver.ipynb
      - BR.INDE (GeoServer): pages/dados/br/inde_geoserver.ipynb
      - BR.IPHAN (GeoServer): pages/dados/br/iphan_geoserver.ipynb
      - BR.MapBiomas: pages/dados/br/map_biomas.ipynb
      - BR.MIDR (GeoServer): pages/dados/br/midr_geoserver.ipynb
      - BR.SFB (SICAR): pages/dados/br/sfb_sicar.ipynb
      - BR.SFB (GeoServer): pages/dados/br/sfb_geoserver.ipynb
      - BR.SFB (Class): pages/dados/br/sfb_class.ipynb
      - BR.SNISB: pages/dados/br/snisb.md

  - Dados (São Paulo):
      - SP.CATI: pages/dados/sp/cati.md
      - SP.CATI - Urbanizado (2016): pages/dados/sp/cati_exemplo.ipynb
      - SP.CETESB: pages/dados/sp/cetesb.md
      - SP.CETESB (Exemplos): pages/dados/sp/cetesb_divamin.ipynb
      - SP.DAEE: pages/dados/sp/daee_geoserver.ipynb
      - SP.DataGeo (GeoServer): pages/dados/sp/datageo_geoserver.ipynb
      - SP.Defesa Civil: pages/dados/sp/defesa_civil_divamin.ipynb
      - SP.MPSP: pages/dados/sp/mpsp_pooch.ipynb
      - SP.SP: pages/dados/sp/sp_pooch.ipynb
      - SP.TJSP: pages/dados/sp/tjsp.ipynb

  - Dados (Paraná):
      - PR.CELEPAR (GeoServer): pages/dados/pr/celepar_geoserver.ipynb

  - Dados (Espírito Santo):
      - ES.Geobases (GeoServer): pages/dados/es/geobases_geoserver.ipynb

  - Outros:
      - Atlas Rural de Piracicaba: pages/dados/outros/sp_atlas_rural_piracicaba.ipynb
      - APA Corumbataí: pages/dados/outros/sp_ff_apa_corumbatai.ipynb
      - Santos, SP (GeoServer): pages/dados/outros/santos_geoserver.ipynb
      - Piracicaba: pages/dados/outros/sp_piracicaba.ipynb
      - Plano das Bacias PCJ 2020-2035: pages/dados/outros/sp_bh_pcj_2020_2035.ipynb
      - Plano da Bacia Hidrográfica do Alto Tietê (2018): pages/dados/outros/sp_bh_at.ipynb
      - Outros Dados: pages/dados/outros_dados.md

  - Rasters:
      - Tiles: pages/dados/raster/tiles.ipynb
      - CBERS: pages/dados/raster/cbers.ipynb

  #     - Gerenciamento de Perfil: scripts/gerenciamento_perfil.ipynb
  #     - Consulta de Processos: scripts/consulta_processo.ipynb
  # - Histórico: pages/histórico.md
  # - Como Contribuir?: pages/como-contribuir.md
  # - Page Object Model: pages/pacote.md
  # - Bugs: pages/bugs.md
  # - Intimações: pages/intimações.md
  # - Me, Myself and I: pages/autor.md

theme:
  name: material

  custom_dir: docs/overrides

  language: pt-BR

  # Breadcrumbs
  features:
    - navigation.path
    - navigation.top
    #- navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.follow
    #- toc.integrate
    - content.code.annotation
    - content.code.copy

  icon:
    repo: fontawesome/brands/github
    favicon: attachment/favicon-32x32.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji # Suporte a emojis
  - pymdownx.tasklist # Suporte à tarefas
  - pymdownx.mark # Marcado
  - pymdownx.tilde # Realçado
  - pymdownx.highlight # Código
  #  - pymdownx.superfences:
  #      custom_fences:
  #        - name: mermaid
  #          class: mermaid
  #          format: !!python/name:pymdownx.superfences.fence_code_format
  #            # Referências
  #            # https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/mkdocs.yml

  # https://pypi.org/project/mkdocs-pdf/
  - attr_list

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true
      separator: "_"

  # - pymdownx.pathconverter:
  #     base_path: "open-geodata" # default: ''
  #     relative_path: "" # default ''
  #     absolute: true # default: false
  #     tags: "a script img link object embed"

plugins:
  - search:
      lang: pt
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

  - tags:
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      tags_slugify_format: "tag:{slug}"
      #tags_hierarchy: true

  - social:
      #cards_layout: default
      cards_layout_options:
        background_color: "#ff1493"
        background_image: docs/assets/bug-paginacao.png
        color: "#ffffff"
        #font_family: Ubuntu
        # logo: docs/assets/logo.png
        #title: My custom title

  #- projects
  - mkdocs-jupyter:
      ignore_h1_titles: True
      include_source: True
      execute: false
      show_input: True # Default True
      no_input: False # Default False
      #ignore: [ '1*.ipynb' ]
      include: ["*.ipynb"] # Default: ["*.py", "*.ipynb"]
      remove_tag_config:
        remove_cell_tags:
          - hide_code

  # https://pypi.org/project/mkdocs-pdf/
  - mkdocs-pdf

  # https://mkdocs-mermaid2.readthedocs.io/en/latest/#configuration
  #- mermaid2

extra:
  analytics:
    provider: google
    property: GT-PZVTRDZX

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/michelmetran
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/michelmetran/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/michelmetran

  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#versioning
  # version:
  #   provider: mike

extra_javascript:
  #- optionalConfig.js
  - https://cdn.jsdelivr.net/npm/mermaid@11.5.0/dist/mermaid.min.js
  #- extra-loader.js
