{% set name = "open-geodata" %}
{% set version = "23.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/open_geodata-{{ version }}.tar.gz
  sha256: c449040a9e0a6e5a2dde49894b8a53caf8e10f07384538f1908cf4358552500b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - uv_build
    - pip
  run:
    - python >=3.11
    - folium >=0.19.7
    - geopandas >=1.1.0
    - mapclassify >=2.9.0
    - matplotlib-base >=3.10.3
    - more-itertools >=10.7.0
    - pandas >=2.3.0
    - py7zr >=1.0.0
    - selenium >=4.33.0
    - sicar
    - sidrapy >=0.1.4

test:
  imports:
    - open_geodata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/open-gedata/
  summary: Dados Espaciais do Brasil
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michelmetran
