name: Publish Python to PyPI

on: push

jobs:
  build-n-publish:
    name: Build and Publish Python Poetry🐍 distributions 📦 to Conda

    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Check out repository
        uses: actions/checkout@v4

      # https://github.com/astral-sh/setup-uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      # https://github.com/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # python-version: '3.11'
          # python-version-file: '.python-version'
          python-version-file: 'pyproject.toml'

      - name: Lock UV dependencies
        run: uv lock

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build
        run: uv build

        # https://www.pyopensci.org/python-package-guide/tutorials/publish-conda-forge.html
        # https://freedium.cfd/medium.com/analytics-vidhya/publish-a-python-package-to-conda-b352eb0bcb2e
      - name: Grayskull
        run: pip install grayskull && grayskull pypi open-geodata

      # - name: Publish
      #   run: uv publish --token ${{ secrets.PYPI_TOKEN }}

      # https://github.com/marketplace/actions/publish-conda
      # - name: publish-to-conda
      #   uses: fcakyon/conda-publish-action@v1.3
      #   with:
      #     subdir: 'conda'
      #     anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
      #     platforms: 'win osx linux'

      # https://github.com/marketplace/actions/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge,michelmetran
          python-version: ${{ matrix.python-version }}
          activate-environment: test

      - name: Conda info
        shell: bash -el {0}
        run: conda info

      - name: Conda Install
        shell: bash -el {0}
        run: |        
          conda install anaconda-client
          conda install conda-build

      - name: Conda list
        shell: pwsh
        run: conda list

      - name: Publish distribution 📦 to Anaconda if Push
        shell: bash -l {0}
        run: |

          PKG_NAME=open-geodata
          mkdir ~/conda-bld
          conda config --set anaconda_upload no
          conda build "conda/"
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u ${{ secrets.CONDA_USERNAME }} /usr/share/miniconda/conda-bld/noarch/$PKG_NAME-$VERSION-py_0.tar.bz2 --force
